image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - dist/

Build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - dist/

